### PR TITLE
Create `Slider` component to wrap `Wallop`

### PR DESCRIPTION
**Pull request by jjenzz**
I noticed the discussion around re-using Wallop, had a few spare mins so created a component.

Can hopefully be re-used in https://github.com/fathomlondon/fathomlondon.com/pull/205

### CODE REVIEW

**Comment by peduarte** [comment]
Good stuff @jjenzz thank you!

The build is failing because the wallop package has some issues with yarn. I'm not sure what's going on.

The plan is to remove wallop ASAP! 😂 

Maybe to keep things simple we can keep the `wallop.min.js` file and load it via the `react-script` packages?

**Comment by peduarte** [comment]
Deploy preview for *fathomlondon* ready!

Built with commit 7199d2c55e029ad291ed0a0b0b84489ed0ad8bcf

https://deploy-preview-208--fathomlondon.netlify.com

**Comment by jjenzz** [comment]
@peduarte Ah, that's because `Wallop` references `window` so fails when Gatsby does it's server rendering (there's no `window` on the server). 

I've wrapped the script in a `if (typeof window !== 'undefined) {` check in `utils/wallop.js` to get around this. Let me know if you're happy with this as an interim solution. Wasn't really sure where to save this file 🤷‍♂️

**Comment by peduarte** [comment]
@jjenzz I think this is fine for now 👍

**Comment by peduarte** [comment]
@AndrewJDick and @jfidiles can you both review this, merge and then implement in your PRs.

Thanks

**Pull request merged**
