### PR TITLE
New JD

### PR DESCRIPTION
**Pull request by saracmcorreia**

### CODE REVIEW

**Comment by peduarte** [comment]
Deploy preview for *fathomlondon* ready!

Built with commit ba01b7c2df9a3bd08a545a3b6d228af9e63b2672

https://deploy-preview-198--fathomlondon.netlify.com

**Comment by peduarte** [comment]
Thanks @saracmcorreia. Unfortunately we're in code freeze mode :(  This is because we're right in the middle of migrating from Jekyll to Gatsby.

**Comment by ibrennan** [comment]
@peduarte even for content change like this? It's a critical role we are hiring for Anaplan

**Comment by peduarte** [comment]
@ibrennan I turned off Auto Publishing from Netlify to avoid breaking the live site. If you're confident we can merge this to master, deploy to Netlify without breaking the live site, then I'm happy to merge. 

My main concern here is breaking the live site as I've changed the build scripts within Netlify alreadty.

**Comment by ibrennan** [comment]
> I've changed the build scripts within Netlify already 

Oh. 

Judging by the build preview: https://deploy-preview-198--fathomlondon.netlify.com/ then it will be a problem deploying 😂

**Comment by ibrennan** [comment]
Sorry @saracmcorreia 

Closing this, we'll have to promote this on other channels and not put it on the website. We're mid-flight with making large improvements to the site, which will have a CMS making things much easier to update 👍

**Comment by saracmcorreia** [comment]
No worries! :)

**Pull request closed without merging**
